const character ={
    
    smiling:{ path:"Face_R" , type: "i", value: 1   },
    happy:{ path:"Face_R" , type: "i", value: 1   },
    smile:{ path:"Face_R" , type: "i", value: 1   },
    shy:{ path:"Face_R" , type: "i", value: 2   },
    embarrassed:{ path:"Face_R" , type: "i", value: 2   },
    embarrassing:{ path:"Face_R" , type: "i", value: 2   },
    blush:{ path:"Face_R" , type: "i", value: 2   },
    red:{ path:"Face_R" , type: "i", value: 2   },
    wink:{ path:"Face_R" , type: "i", value: 3   },
    bored:{ path:"Face_R" , type: "i", value: 4   },
    bore:{ path:"Face_R" , type: "i", value: 4   },
    boring:{ path:"Face_R" , type: "i", value: 4   },
    bought:{ path:"Face_R" , type: "i", value: 4   },
    brought:{ path:"Face_R" , type: "i", value: 4   },
    angry:{ path:"Face_R" , type: "i", value: 5   },
    wow:{ path:"Face_R" , type: "i", value: 6   },
    thank:{ path:"Face_R" , type: "i", value: 7   },
    thanks:{ path:"Face_R" , type: "i", value: 7   },
    shock:{ path:"Face_R" , type: "i", value:  8  },
    shocked:{ path:"Face_R" , type: "i", value:  8  },
    love:{ path:"Face_R" , type: "i", value:  9  },
    loved:{ path:"Face_R" , type: "i", value:  9  },
    disgusting:{ path:"Face_R" , type: "i", value:  10  },
    disappointed:{ path:"Face_R" , type: "i", value:  10  },
    disappointing:{ path:"Face_R" , type: "i", value:  10  },
    disappoint:{ path:"Face_R" , type: "i", value:  10  },
    yuck:{ path:"Face_R" , type: "i", value:  10  },
    sad:{ path:"Face_R" , type: "i", value:  11  },
    cry:{ path:"Face_R" , type: "i", value:  11  },
    crying:{ path:"Face_R" , type: "i", value:  11  },
    horny:{ path:"Face_R" , type: "i", value:  12  },
    nude:{ path:"Face_R" , type: "i", value:  12  },
    horney:{ path:"Face_R" , type: "i", value:  12  },
    newt:{ path:"Face_R" , type: "i", value:  12  },
    lewd:{ path:"Face_R" , type: "i", value:  12  },
    faceless:{path:"Face_R" , type: "i", value: 0 },
    faithless:{path:"Face_R" , type: "i", value: 0 },
    emotionless:{path:"Face_R" , type: "i", value: 0 },
    made:{path:"Masamu_Clothes" , type: "i", value: 3 },
    mate:{path:"Masamu_Clothes" , type: "i", value: 3 },
    med:{path:"Masamu_Clothes" , type: "i", value: 3 },
    mit:{path:"Masamu_Clothes" , type: "i", value: 3 },
    maid:{path:"Masamu_Clothes" , type: "i", value: 3 },
    topless:{path:"Masamu_Clothes" , type: "i", value: 2 },
    shirtless:{path:"Masamu_Clothes" , type: "i", value: 2 },
    outerwear:{path:"Masamu_Clothes" , type: "i", value: 0 },
    court:{path:"Masamu_Clothes" , type: "i", value: 0 },
    coat:{path:"Masamu_Clothes" , type: "i", value: 0 },
    pigtail:{path: "pigtails_ON", type: "i", value:1 },
    short :{path: "pigtails_ON", type: "i", value:0 },
    shot :{path: "pigtails_ON", type: "i", value:0 },
    human:{path: "ear_tail_off", type: "i", value:1},
    man:{path: "ear_tail_off", type: "i", value:1},
    rabbit:{path: "ear_tail_off", type: "i", value:0},
    fox:{path: "ear_tail_off", type: "i", value:2},
    sideburn:{path: "L.R_Hair_ON", type: "i", value:1},




}
;
module.exports = character;